### ISSUE TITLE
GitHub Repo Connection Problem

### ISSUE THREAD

**Issue by jnrice** [fullstackjournalists/fullstackjournalists#3]
I have double checked that I have git installed on my computer (which I do) and that the version is up to date (version 2.15.1), but it is connected to a repository in GitLab. I am not sure how to connect it to the fullstackjournalists github repo. I have tried googling around to see what the problem might be, but am not even really sure what is wrong. I'm thinking it could be a path problem, but I'm not sure. Should I try to uninstall git and reinstall it? Let me know what you think my next steps should be!

**Comment by lisawilliams** [comment]
Hi, Jordan!  I *think* when you add a remote it should go to the right place...

Try this.  On your Github account, create a new repository.  Then click 'clone or download.' You should see a url like this: `https://github.com/lisawilliams/email-data-science-tutorial.git` except it should contain your username, and whatever name you gave your new repo.  

Then, open terminal and type: 

`git clone https://github.com/lisawilliams/email-data-science-tutorial.git` (with the right url). 

You should now have a file folder with the repo name.  So change into that directory: 

`cd name-of-repo`

Then type `git status` just to make sure everything worked. 

Type `touch readme.md` and then type `ls -a`. You should see the new file you created. 

Now, type `git add -A` (the capitalization is important!) and then type `git commit -m "adding a test file to test my git setup" and hit return. 

Finally, type `git push origin master`. Once you do that, what happens?

**Comment by jnrice** [comment]
I did all of that and I have linked the new repo I made to the folder on my comp. It also has the readme.md file in it. What are my next steps to linking to the fullstackjournalists repo?

**Comment by lisawilliams** [comment]
Jordan -- sounds like it's working!  Now just fork and clone this repository (https://github.com/fullstackjournalists/fullstackjournalists).  Make sure to fork it first, with the fork button in the upper right hand corner. Once you've got a local copy of the fullstackjournalists repo, edit the `members.md` file and add your name. Then commit and push (again following the same instructions as above). You should have your own copy of the repo at github.com/jnrice/fullstackjournalists. 

To officially 'join,' make a pull request -- go to http://github.com/jnrice/fullstackjournalists.  You'll see a tab on your copy of the repo called Pull Requests. Click on that, and make a new pull requests. What this does is send me a notification that you want me to integrate changes you made.  Once I accept your pull request, the official fullstackjournalists repo will have your name on th member list (`members.md`). Hurry and you'll be Official Member #2 :D

**Comment by jnrice** [comment]
I think I did everything right. Let me know if you did not get a notification from my pull request and I can try again!
